### ISSUE TITLE
fatal signal 22

### ISSUE THREAD

**Issue by ralfkalwa** [hannakoppelaar/vcv-modules#1]
Whenever i'll try to load an scl file (from the scale archive) VCV (2.0.6) crashes:

[21.723 fatal adapters/standalone.cpp:49 fatalSignalHandler] Fatal signal 22. Stack trace:
27:  0x0
26: raise 0x7ffe65caabe0
25: abort 0x7ffe65caf1e0
24: ZN7Tunings6TuningC1ERKNS_5ScaleERKNS_15KeyboardMappingEb 0x7ffe2355d540
23: init 0x7ffe23541390
22: ZSt16__introsort_loopIN9__gnu_cxx17__normal_iteratorIP9ScaleStepSt6vectorIS2_SaIS2_EEEExNS0_5__ops15_Iter_comp_iterIZN6XenQnt12updateTuningEPcEUlRKS2_SD_E_EEEvT_SG_T0_T1_ 0x7ffe235bac20
21: ZZN4rack11createModelI6XenQnt12XenQntWidgetEEPNS_6plugin5ModelENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEN6TModelD1Ev 0x7ffe235bf0d0
20: ZZN4rack11createModelI6XenQnt12XenQntWidgetEEPNS_6plugin5ModelENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEN6TModelD1Ev 0x7ffe235bf0d0
19: ZN21MenuItemLoadScalaFile9getParentB5cxx11EPc 0x7ffe23555660
18: ZN21MenuItemLoadScalaFile8onActionERKN4rack6widget6Widget11ActionEventE 0x7ffe23555570
17: ZN4rack2ui8MenuItem8doActionEb 0x7ffe0f5adbf0
16: ZN4rack6widget10EventState12handleButtonENS_4math3VecEiii 0x7ffe0f5b3220
15: ZN4rack6window3Svg4loadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE 0x7ffe0f5b8070
14: glfwPlatformUnlockMutex 0x7ffe0f5f6350
13: CallWindowProcW 0x7ffe66a8e460
12: CallWindowProcW 0x7ffe66a8e460
11: glPushClientAttrib 0x7ffe373a9ec0
10: CallWindowProcW 0x7ffe66a8e460
9: DispatchMessageW 0x7ffe66a8e040
8: glfwPlatformPollEvents 0x7ffe0f5fa590
7: ZN4rack6window6Window4stepEv 0x7ffe0f5b9560
6: ZN4rack6window6Window3runEv 0x7ffe0f5b9f20
5: ZN4rack6window6Window3runEv 0x7ffe0f5b9f20
4: ZN4rack6window6Window3runEv 0x7ffe0f5b9f20
3: ZN4rack6window6Window3runEv 0x7ffe0f5b9f20
2: ZN4rack6window6Window3runEv 0x7ffe0f5b9f20
1: BaseThreadInitThunk 0x7ffe668b7020
0: RtlUserThreadStart 0x7ffe67c82630

**Comment by hannakoppelaar** [comment]
Hi! What OS are you running on? And does this happen with every file from the archive, as far as you can tell?

**Comment by ralfkalwa** [comment]
Hi, 

Windows 10 21h2 and yes it is happening with serveral files i have tried. As a test  i‘ve tried NYSTHI ScalaQuantizer which works.

I will build it from source, maybe that works...

**Comment by ralfkalwa** [comment]
building against Rack-2.1.1 works fine without any errors loading scl files in Rack-2.1.1 an 2.0.6 - hmm...

$ make install
g++ -o plugin.dll build/src/XenQnt.cpp.o build/src/plugin.cpp.o -shared -L/home/rk/VCVRack/Rack -lRack -static-libstdc++
rm -rf dist
mkdir -p dist/h4n4-modules
cp plugin.dll dist/h4n4-modules/
strip -s dist/h4n4-modules/plugin.dll
cp -r --parents res LICENSE  plugin.json dist/h4n4-modules/
cd dist && tar -c h4n4-modules | zstd -19 -o "h4n4-modules"-"2.1.1"-win.vcvplugin
mkdir -p "C:\Users\xxxxxxxx/Documents/Rack2"/plugins/
cp dist/*.vcvplugin "C:\Users\xxxxxxx/Documents/Rack2"/plugins/

**Comment by hannakoppelaar** [comment]
That's because I had just fixed it :) Version 2.1.1 is the new version. 

The code for checking if a directory exists was not exactly portable and its behavior on windows was unspecified ;) 

I will submit a new version to the VCV library over the coming days. I've also added new binaries on github.

**Comment by hannakoppelaar** [comment]
Thanks for testing @orionsunlurca! I'm now closing this issue as fixed by release 2.1.1.

**Comment by ralfkalwa** [comment]
Thanks for your quick response and solution!

Mobil gesendet
