### ISSUE TITLE
Sublicense wording not correct

### ISSUE THREAD

**Issue by dromer** [hannakoppelaar/vcv-modules#3]
Don't want to be pedantic, but the wording of your "[sublicense](https://github.com/hannakoppelaar/h4n4-modules/blob/main/src/tuning/SUBLICENSE)" is not correct I think:

`As bundled with this project it is sublicensed under the same license as the rest of the code, namely the GPL version 3 or later.`

The code you included remains MIT. People can make future changes and keep them closed.
<s>It is not covered by your GPL3+ license in any way, however you are totally free to redistribute the code as is of course.</s>
Changes you make would be GPL3+ though, but the original code license stays intact.

This assumes that you haven't made changes to this library at your initial commit.

**Comment by hannakoppelaar** [comment]
The original license states that the user has the the right "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software". I was hoping to stay away from hairy multi-license issues by simply sublicensing. Am I missing some legal subtlety here?

**Comment by dromer** [comment]
Maybe I'm just misinterpreting :D

Afaik only your changes can be licensed differently, but the original source remains MIT either way.
The main thing is that you keep the original copyright notice.

Since you didn't make any changes to the source there shouldn't be a need to "sublicence", but maybe that's just me :)
