### ISSUE TITLE
FR: Remember last 10 scala files loaded

### ISSUE THREAD

**Issue by fractalgee** [hannakoppelaar/vcv-modules#7]
Number of 10 is arbitrary but would be cool if the last few scala files that were loaded were kept track of, so can be switched to without having to dig through the 2000+ scala files scala directory every time I want to use another one. I have around 10 I often use, so that is how number 10 arose, but I'll leave that to your decision/

**Comment by hannakoppelaar** [comment]
Yeah, that's a useful feature. I'll try to get this implemented next I time I sit down to code.

**Comment by hannakoppelaar** [comment]
This feature is now available in the latest version included in the VCV library.
